### ISSUE TITLE
Trying to open a session on ec2 ubuntu server

### ISSUE THREAD

**Issue by noahjaskolski** [elisescu/tty-share#48]
Getting this error

Cannot proxy the connection to the target HTTP server: dial tcp 127.0.0.1:8000: connect: connection refused tty-share.

What would be causing this? I tried two different internet connections with no luck.

**Comment by noahjaskolski** [comment]
I've tried both a local VM and ec2 instance.

**Comment by elisescu** [comment]
@noahjaskolski pls show how you're running it (and `tty-proxy` if you're running your instance), it's hard to figure out otherwise.

Also check to see that you're not running anything else on port 8000, or use the `-listen` param if you do and choose another port.

Could also be that you may have a firewall that blocks connections, although it's localhost, so probably not the case?

**Comment by elisescu** [comment]
Closing it for now, @noahjaskolski . Feel free to open it if you haven't managed, and I'll try to help based on new info you come back with.
