### ISSUE TITLE
does not work over my corporate firewall

### ISSUE THREAD

**Issue by hjlow** [elisescu/tty-share#5]
love the idea of this and it works well outside my place of work but not from inside. any more information you need?

**Comment by elisescu** [comment]
Thanks, @hjlow! I imagine it is probably because your network setup is blocking the ports tty-share uses.
I can't suggest any simple workaround to that, unfortunately. Maybe using websockets for both ends, over port 80, could trick firewalls and allow the connection, but that would take some time to implement. I hope I will get time some day to get to it.
